### ISSUE TITLE
有个问题

### ISSUE THREAD

**Issue by Ma-PC** [datadrivenwheels/DUST#1]
看了您的文章有点灵感，感谢您的贡献。
我运行 step_fusion_3d_get_feature 时报错，加载预训练模型的权重文件时，当前模型的结构和预训练模型的结构不匹配。
step_fusion_3d_get_feature 和 step_fusion_3d 中的预训练模型通道数不一致，我该如何调整？
![96](https://github.com/user-attachments/assets/51788391-d7e4-44d8-a5ec-b97f9d55f574)
![128](https://github.com/user-attachments/assets/504ad446-6c4d-4b6d-8131-ab5b9e1185fb)
![报错](https://github.com/user-attachments/assets/54d12105-4d42-4e3c-bcc3-6d8e6cc97cac)

**Comment by shiliangcn** [comment]
感谢关注，我觉得问题出在 model 定义上的 embed_dim上，模型中的默认 embed_dim=96，需要指定成128。
model = SwinTransformer3D(num_classes=4,
                              embed_dim = 128,
                               mlp_ratio=4.0,
                               patch_norm=True,
                               patch_size=(2,4,4,),
                               drop_path_rate=0.1, # stochastic depth rate in the paper
                               num_heads=[4,8,16,32],
                               depth = [2,2,18,2],
                        pretrained='https://download.openmmlab.com/mmaction/v1.0/recognition/swin/swin_base_patch4_window7_224.pth',
                               pretrained2d=True,
                               window_size=(8,7,7,))

**Comment by yixin-c** [comment]
@Ma-PC step_fusion_3d_get_feature.py 中的定义的model和step_fusion_3d.py里定义的不一样，我们已经更正并push了，请重新pull再试试。感谢！

**Comment by Ma-PC** [comment]
感谢您的回复，看了您的文章和代码，我觉得对我很有用，您能告诉我一下您的数据集结构吗？我想用自己的数据集跑一下代码，如果您愿意分享的话：mpc960902@163.com
